"""Initial migration

Revision ID: fedf24e86514
Revises: 
Create Date: 2026-08-18 23:02:06.866302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedf24e86514'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_jobs_company', 'jobs', ['company'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_company', table_name='jobs')
    # ### end Alembic commands ###
